filter:
    excluded_paths: [vendor/*]

before_commands:
  - "composer install --prefer-source"

tools:
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            excluded_paths: ["vendor/*", "spec/*"]
        config:
            standard: PSR2

    php_code_coverage:
        enabled: true
        test_command: phpunit

    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]

    php_cpd:
        command: phpcpd
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs: ["vendor", "spec"]
        enabled: true

    php_pdepend:
        enabled: true
        excluded_dirs: ["vendor", "spec"]

    php_loc:
        enabled: true
        excluded_dirs: ["vendor", "spec"]

    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]

    sensiolabs_security_checker: true
